name: Bounties
version: '${project.version}'
main: me.bribedjupiter.quests.Main
api-version: 1.19
authors: [ BribedJupiter ]
description: Adds Bounties to your minecraft server!
depend: [Essentials, Vault]

commands:
  bounty:
    description: Sets a bounty on a player. Do /bounty help to learn how to use the plugin.
    aliases: [ bn ]
    permission: bounties.*
    usage: |
      You can use /bn instead of /bounty.
      Player usage:
      /bounty place [target player] [$ reward] - Allows you to place a bounty on a target for a monetary reward.
      /bounty edit [target player] [$ reward] - Allows you to edit the reward of a bounty you've placed on a player.
      /bounty list - Lists all active bounties.
      /bounty remove [target player] - Allows you to delete your bounty on a specific player and get a refund.
      /bounty pay [player who placed the bounty on you] - Allows you to pay off a bounty placed on you by someone else.
      Admin usage:
      Edit the reward of any bounty --> /bounty edit [target] [player who placed the bounty] [reward] - (Does not refund players)
      Remove any bounty --> /bounty remove [target] [player who placed the bounty] - (Does not refund players)
      Clear all bounties --> /bounty clearall - (Does not refund players)

permissions:
  bounties.*:
    descrpition: Allows access to the plugin's functionality.
    default: true
  bounties.admin:
    description: Allows the user to edit, remove, and clear all bounties, including the ones that aren't theirs. If someone with this permission removes or edits someone else's bounty, they will not receive a refund and money will not be taken from their account. There is a possibility of abuse or cheating so grant this permission sparingly.
    default: op

