name: Bounties
version: '1.1-DEBUG'
main: me.bribedjupiter.quests.Main
api-version: 1.19
authors: [ BribedJupiter ]
description: Adds Bounties to your minecraft server!
depend: [Essentials, Vault]

commands:
  bounty:
    description: Sets a bounty on a player. Do /bounty help to learn how to use the plugin.
    aliases: [ bn ]
    permission: bounties.*
    usage: |
      You can use /bn instead of /bounty.
      /bounty place [target] $reward - Allows you to place a bounty on a target for a monetary reward.
      /bounty edit [target] $reward - Allows you to edit a bounty you've placed on a certain player. With the permission "bounties.admin", one can edit any bounty by following this syntax: /bounty edit [target] [placer] $reward, though it will not give a refund to the original placer if used in this way.
      /bounty list - Lists all active bounties.
      /bounty remove [player] - Allows you to remove your bounty on a specific player. With the permission "bounties.admin", one can remove any bounty by following this syntax: /bounty remove [target] [placer], though it will not give a refund to the original placer if used in this way.
      /bounty clearall - Allows you to remove all active bounties without providing refunds to the placers. Requires the permission "bounties.admin".

permissions:
  "bounties.*":
    descrpition: Allows access to the plugin's functionality.
    default: true
  "bounties.admin":
    description: Allows the user to edit, remove, and clear all bounties, including the ones that aren't theirs. If someone with this permission removes or edits someone else's bounty, they will not receive a refund and money will not be taken from their account. There is a possibility of abuse or cheating so grant this permission sparingly.
    default: op

